### ISSUE TITLE
TimeTable doesn't open

### ISSUE THREAD

**Issue by w3code** [willyb321/electron-menubar-timetable#53]
Hi There!

Today I've installed your app (downloaded the .dmg-file, macOS Sierra).

If I try to open the app, there's an alert:

![timetable-app](https://cloud.githubusercontent.com/assets/10848785/20636388/68e055cc-b36c-11e6-91d4-e5b6a34b24f0.png)

**Comment by willyb321** [comment]
Whoops! I'll get a new build up ASAP.

**Comment by w3code** [comment]
Ok, thanks for your very quick response! 👍

**Comment by willyb321** [comment]
In the meantime you could probably download an older build (just fyi)

**Comment by willyb321** [comment]
For example, https://github.com/willyb321/electron-menubar-timetable/releases/download/build-490-master-2016-10-20-01-58/TimeTable-darwin-x64.zip

**Comment by w3code** [comment]
Ok, thanks, I will try it out. 👍

**Comment by willyb321** [comment]
@w3code ok this should in theory be fixed in the latest version. Sorry for late reply! Been quite busy!

**Comment by w3code** [comment]
No problem for the late reply, @willyb321 . But it still doesn't work.

I made a clean install, but there's still this error:
![bildschirmfoto 2016-12-21 um 12 47 32](https://cloud.githubusercontent.com/assets/10848785/21388328/13cfea38-c77c-11e6-8ce6-359e1ac88951.png)

**Comment by willyb321** [comment]
ah, ive actually fixed it this time, ill ping you when the release goes up. Its building now!

**Comment by willyb321** [comment]
BTW, the problem was a capital letter. LOL

**Comment by w3code** [comment]
Oh, I'm sorry, a misunderstanding. :)

**Comment by w3code** [comment]
Yeah, sometimes the errors seem to be big, but they aren't. :D

**Comment by willyb321** [comment]
Lol yep. I was trying to set the icon to IconTemplate.png but its called iconTemplate.png lol

**Comment by willyb321** [comment]
Ok, its now up.
